### ISSUE TITLE
コードレビュー：hobbies_controller#random 

### ISSUE THREAD

**Issue by yuki-nishimoto1109** [jun0033/osituke_app#53]
# hobbies_controller#random
主な変更点

 1. ランダム表示Hobbyの抽出方法変更
 2. return の使用
---
## 1. ランダム表示Hobbyの抽出方法変更
```
[元コード]
  comments = HobbyComment.includes(:hobby).where.not(user_id: current_user.id)
  hobbies = Hobby.where(is_draft: false).where.not(user_id: current_user.id).where.not(id: comments.pluck(:hobby_id))
  @hobby = hobbies.offset( rand(hobbies.size) ).first
```
```
# ランダム表示用のデータを用意
  done_hobby_ids = current_user.hobby_comments.done.pluck(:hobby_id)
  todo_hobby_ids = current_user.to_does.pluck(:hobby_id)
  undone_hobbies =
    Hobby.where(is_draft: false)               # 下書きでないもの
         .where.not(user_id: current_user.id)  # ログインユーザーの投稿でない
         .where.not(id: done_hobby_ids)        # ログインユーザーが実施済でない
         .where.not(id: todo_hobby_ids)        # ログインユーザーのToDoにない
  @hobby = undone_hobbies.shuffle.first
```

Point
- 変数名の変更.追加
	- done_hobby_ids 	: ログインユーザーがやったhobbyのid一覧を取得
	- todo_hobby_ids	: ログインユーザーがToDoリストに追加しているhobbyのid一覧を取得
	- undone_hobbies	: ログインユーザーがやっていないhobbyの一覧を取得
	- @ hobby : ランダムで表示するhobbyを１つ代入
- データ取得メソッドの変更
	- done_hobby_ids	: 
		- .done（enumの機能）を使用して完了報告コメント一覧を取得
		- .pluck(:hobby_id) でid一覧を配列で取得
	- @ hobby :
		- undone_hobbies内をsshuffleして一番目を取得

## 2. return の使用
[元コード省略]

---

    def random
      flash[:info] = 'ログインしました'
    + return redirect_to hobbies_path unless current_user.can_display_random?
      # ランダム表示用のデータを用意
      --- 省略 ---
    + return redirect_to hobbies_path unless @hobby.present?
      # userのタイマーをリセット
      current_user.update(last_random_displayed_at: Time.now)
      # ToDoに自動保存
      to_does = current_user.to_does.new(hobby_id: @hobby.id)
      to_does.save
    end

if文で書くことは悪くはないが、returnで早く返すことが分かり良い時の方が多い
イメージとして、、、

    def ~~~
	    # まず、実施前に諸所チェック
	    # 次に、メインのプログラム
	    # 最後、終了処理を行う 
    end
というか書き方で自分はやってた。ご参考までに。

---

    [最終コード]
    def random
      flash[:info] = 'ログインしました'
      return redirect_to hobbies_path unless current_user.can_display_random?
      # ランダム表示用のデータを用意
      done_hobby_ids = current_user.hobby_comments.done.pluck(:hobby_id)
      todo_hobby_ids = current_user.to_does.pluck(:hobby_id)
      undone_hobbies =
        Hobby.where(is_draft: false)               # 下書きでないもの
             .where.not(user_id: current_user.id)  # ログインユーザーの投稿でない
             .where.not(id: done_hobby_ids)        # ログインユーザーが実施済でない
             .where.not(id: todo_hobby_ids)        # ログインユーザーのToDoにない
      @hobby = undone_hobbies.shuffle.first
      return redirect_to hobbies_path unless @hobby.present?
      # userのタイマーをリセット
      current_user.update(last_random_displayed_at: Time.now)
      # ToDoに自動保存
      to_does = current_user.to_does.new(hobby_id: @hobby.id)
      to_does.save
    end

**Comment by jun0033** [comment]
ご意見ありがとうございます。returnの使用でわかりやすいし綺麗なコードになりますね！
Hobbyの抽出方法も元のコードより間違いが起こりにくい綺麗なコードだと思います。
一部、完了報告のコメントのみでなくコメントを残したことがある投稿は出てこないものとしてレビューを参考に修正し下記を最終的なコードとします。
def random
    flash[:info] = 'ログインしました'
    return redirect_to hobbies_path unless current_user.can_display_random?
    # ページの表示内容を設定
    seen_hobby_ids = current_user.hobby_comments.pluck(:hobby_id)
    todo_hobby_ids = current_user.to_does.pluck(:hobby_id)
    undone_hobbies =
    Hobby.where(is_draft: false)               # 公開設定の投稿
         .where.not(user_id: current_user.id)  # ログインユーザーの投稿でない
         .where.not(id: seen_hobby_ids)        # ログインユーザーがコメントを残してない
         .where.not(id: todo_hobby_ids)        # ログインユーザーのToDoにない
    @hobby = undone_hobbies.shuffle.first
    return redirect_to hobbies_path unless @hobby.present?
    current_user.update(last_random_displayed_at: Time.now)
    # ToDoに自動保存
    to_does = current_user.to_does.new(hobby_id: @hobby.id)
    to_does.save
  end
