### ISSUE TITLE
コードレビュー：_header.html.erb

### ISSUE THREAD

**Issue by yuki-nishimoto1109** [jun0033/osituke_app#54]
# _header.html.erb
主な変更点
 1. admin_header / public_header の分離

## 1. admin_header / public_header の分離
admin_signed_in? / user_signed_in? で分岐して表示変更している部分が複数個所あり読みにくい
admin_headerとpublic_headerのテンプレートを作ることで、分岐を一度だけにする
テンプレートの名前については_header_xxxx.html.erbにすることで_header.html.erbの子要素であるような感じを出した。
個人的には非常にセンスのある命名をしたと思う。ありがとうございます。
*検索フォームもテンプレート化してもいいかも

---
    [_header.html.erb]
    <% if admin_signed_in? %>
      <%= render "layouts/header_admin" %>
    <% elsif user_signed_in? %>
      <%= render "layouts/header_public" %>
    <% else %>
      <nav class="navbar navbar-expand-lg">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <div class = "header_inner">
            <% if request.fullpath.include? ("/admin") %>
              <%= link_to image_tag("osituke2.png", size: '100x100', alt: "ositukeロゴ"),admin_root_path %>
            <% else %>
              <%= link_to image_tag("osituke2.png", size: '100x100', alt: "ositukeロゴ"),root_path %>
            <% end %>
          </div>
        </div>
      </nav>
    <% end %>
---
    [_header_admin.html.erb]
    <div class="top-color">
      <div class="row text-center">
        <div class="col-10 search_form">
          <%= form_with url: searches_search_path, local: true, method: :get do |f| %>
            <%= f.select :range, options_for_select([['趣味'], ['ユーザー']]) %>
            <%= f.text_field :word %>
            <%= f.button type: "submit", class: "btn btn-primary btn-sm", style: "vertical-align: top;" do %>
              <i class="fas fa-search"></i>
            <% end %>
          <% end %>
        </div>
        <div class="col-2">
        <%= link_to "ログアウト",destroy_admin_session_path, method: :delete %>
        </div>
      </div>
    </div>
    
    <nav class="navbar navbar-expand-lg band-color p-0">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon white"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <div class = "header_inner">
          <%= link_to image_tag("osituke2.png", size: '100x100', alt: "ositukeロゴ"),admin_hobbies_path %>
        </div>
        <ul class="navbar-nav mx-auto">
          <li><%= link_to "趣味一覧",     admin_hobbies_path,            class: "nav-link white" %></li>
          <li><%= link_to "ランキング",   rank_index_admin_hobbies_path, class: "nav-link white" %></li>
          <li><%= link_to "ジャンル一覧", admin_genres_path,             class: "nav-link white" %></li>
          <li><%= link_to "タグ一覧",     admin_tags_path,               class: "nav-link white" %></li>
          <li><%= link_to "ユーザ一覧",   admin_users_path,              class: "nav-link white" %></li>
        </ul>
      </div>
    </nav>
 ---

     [_header_public.html.erb]
     <div class="top-color">
      <div class="row text-center">
        <div class="col-10 search_form">
          <%= form_with url: searches_search_path, local: true, method: :get do |f| %>
            <%= f.select :range, options_for_select([['趣味'], ['ユーザー']]) %>
            <%= f.text_field :word %>
            <%= f.button type: "submit", class: "btn btn-primary btn-sm", style: "vertical-align: top;" do %>
              <i class="fas fa-search"></i>
            <% end %>
          <% end %>
        </div>
        <div class="col-2">
        <%= link_to "ログアウト",destroy_user_session_path, method: :delete %>
        </div>
      </div>
    </div>
    
    <nav class="navbar navbar-expand-lg band-color p-0">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon white"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <div class = "header_inner">
          <%= link_to image_tag("osituke2.png", size: '100x100', alt: "ositukeロゴ"),hobbies_path %>
        </div>
        <ul class="navbar-nav mx-auto">
          <li><%= link_to "趣味一覧",     hobbies_path,                    class: "nav-link white" %></li>
          <li><%= link_to "ランキング",   rank_index_hobbies_path,         class: "nav-link white" %></li>
          <li><%= link_to "ジャンル一覧", genres_path,                     class: "nav-link white" %></li>
          <li><%= link_to "タグ一覧",     tags_path,                       class: "nav-link white" %></li>
          <li><%= link_to "ToDoリスト",   to_does_user_path(current_user), class: "nav-link white" %></li>
          <li><%= link_to "下書き",       draft_index_hobbies_path,        class: "nav-link white" %></li>
          <li><%= link_to "マイページ",   user_path(current_user),         class: "nav-link white" %></li>
          <li class= "my-auto">
            <%= link_to notifications_path do %>
              <% if unchecked_notifications.any? %>
                <span class="fa-stack">
                  <i class="fa-regular fa-bell fa-stack-2x white"></i>
                  <i class="fas fa-circle n-circle fa-stack-1x"></i>
                </span>
                <span class= "yellow">new</span>
              <% else %>
                <i class="fa-regular fa-bell white"></i>
              <% end %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

**Comment by jun0033** [comment]
部分テンプレートの提案素晴らしいです。
命名もセンスが光り輝いております。
とても見やすい簡潔なコードになりました。
検索フォームもテンプレート化しbootstrapの調整をしました。
[_header.html.erb]
`<% if admin_signed_in? %>
  <%= render "layouts/header_admin" %>
<% elsif user_signed_in? %>
  <%= render "layouts/header_public" %>
<% else %>
  <nav class="navbar navbar-expand-lg">
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <div class = "header_inner">
        <% if request.fullpath.include? ("/admin") %>
          <%= link_to image_tag("osituke2.png", size: '100x100', alt: "ositukeロゴ"),admin_root_path %>
        <% else %>
          <%= link_to image_tag("osituke2.png", size: '100x100', alt: "ositukeロゴ"),root_path %>
        <% end %>
      </div>
    </div>
  </nav>
<% end %>`

[_header_admin.html.erb]
`<div class="top-color">
  <div class="row text-center">
    <div class="col-4 offset-4 search_form">
      <%= render "searches/searchform" %>
    </div>
    <div class="col-2 offset-2">
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
    </div>
  </div>
</div>

<nav class="navbar navbar-expand-lg band-color p-0">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon white"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <div class = "header_inner">
      <%= link_to image_tag("osituke2.png", size: '100x100', alt: "ositukeロゴ"),admin_hobbies_path %>
    </div>
    <ul class="navbar-nav mx-auto">
      <li><%= link_to "趣味一覧",     admin_hobbies_path,            class: "nav-link white" %></li>
      <li><%= link_to "ランキング",   rank_index_admin_hobbies_path, class: "nav-link white" %></li>
      <li><%= link_to "ジャンル一覧", admin_genres_path,             class: "nav-link white" %></li>
      <li><%= link_to "タグ一覧",     admin_tags_path,               class: "nav-link white" %></li>
      <li><%= link_to "ユーザ一覧",   admin_users_path,              class: "nav-link white" %></li>
    </ul>
  </div>
</nav>`

 [_header_public.html.erb]
`<div class="top-color">
  <div class="row text-center">
    <div class="col-4 offset-4 search_form">
      <%= render "searches/searchform" %>
    </div>
    <div class="col-2 offset-2">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    </div>
  </div>
</div>

<nav class="navbar navbar-expand-lg band-color p-0">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon white"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <div class = "header_inner">
      <%= link_to image_tag("osituke2.png", size: '100x100', alt: "ositukeロゴ"),hobbies_path %>
    </div>
    <ul class="navbar-nav mx-auto">
      <li><%= link_to "趣味一覧",     hobbies_path,                    class: "nav-link white" %></li>
      <li><%= link_to "ランキング",   rank_index_hobbies_path,         class: "nav-link white" %></li>
      <li><%= link_to "ジャンル一覧", genres_path,                     class: "nav-link white" %></li>
      <li><%= link_to "タグ一覧",     tags_path,                       class: "nav-link white" %></li>
      <li><%= link_to "ToDoリスト",   to_does_user_path(current_user), class: "nav-link white" %></li>
      <li><%= link_to "下書き",       draft_index_hobbies_path,        class: "nav-link white" %></li>
      <li><%= link_to "マイページ",   user_path(current_user),         class: "nav-link white" %></li>
      <li class= "my-auto">
        <%= link_to notifications_path do %>
          <% if unchecked_notifications.any? %>
            <span class="fa-stack">
              <i class="fa-regular fa-bell fa-stack-2x white"></i>
              <i class="fas fa-circle n-circle fa-stack-1x"></i>
            </span>
            <span class= "yellow">new</span>
          <% else %>
            <i class="fa-regular fa-bell white"></i>
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>`

 [_searchform.html.erb]
`<%= form_with url: searches_search_path, local: true, method: :get do |f| %>
  <%= f.select :range, options_for_select([['趣味'], ['ユーザー']]) %>
  <%= f.text_field :word %>
  <%= f.button type: "submit", class: "btn btn-primary btn-sm", style: "vertical-align: top;" do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>`
