### ISSUE TITLE
コードレビュー：application.html.erb

### ISSUE THREAD

**Issue by yuki-nishimoto1109** [jun0033/osituke_app#55]
# application.html.erb
主な変更点

 1. flashメッセージの共通記述
---
## 1. flashメッセージの共通記述
各viewページにflashメッセージを表示する <%= flash[:notice] %> 等の記述があるが、
application.html.erb で共通記述する方が良いと思われる。
[元コード省略]

---

    <body class="d-flex flex-column vh-100 wall">
        <header class="fixed-top"><%= render 'layouts/header' %></header>
        <main class= "mb-auto">
    +     <%= render "layouts/flash" %>
          <%= yield %>
        </main>
        <footer><%= render 'layouts/footer' %></footer>
      </body>

**Comment by jun0033** [comment]
確かにまとめられるところはまとめた方がいいですね！
ありがとうございます！
