### ISSUE TITLE
コードレビュー：hobbies_controller#show

### ISSUE THREAD

**Issue by yuki-nishimoto1109** [jun0033/osituke_app#58]
# hobbies_controller#show
### ＊viewページも変更の必要があるため、注意
主な変更点

 1. 不要インスタンス変数の削除
---
## 1. 不要インスタンス変数の削除
```
[元コード]
  def show
    @hobby = Hobby.includes(:user, :hobby_comments, :tags).find(params[:id])
    @user = @hobby.user
    @comment = current_user.hobby_comments.new(hobby_id: @hobby.id)
    @comments = @hobby.hobby_comments.all.page(params[:page])
    @favorite = Favorite.find_by(hobby_id: @hobby.id)
    # 自分の完了報告があるか調べる
    @report_comment = @comments.find_by(user_id: current_user.id, done_status: true)
    @tags = @hobby.tags
  end
```

アソシエーションを利用して取れるものは変数化しない方が良いと思われる。
ただし、変数化した方が記述が整理される等、特に必要な理由がある場合にはこの限りではない。
その為、ページネーション用の変数はcontroller内で用意している。

完了報告の有無に使っている @ report_comment については、view内の記述を変更して削除可能
（hobbyモデルにログインユーザーが完了報告しているかのmethodを追加）

    - <% unless @report_comment.present? %>
    + <% unless @hobby.done_by?(current_user) %>
        <%= render "public/hobby_comments/done_form" %>
      <% end %>
    
    [model: hobby]
    + def done_by?(user)
	+   hobby_comments.done.exists?(user_id: user.id)
	+ end

---

    [最終コード]
	  def show
	    @hobby = Hobby.includes(:user, :hobby_comments, :tags).find(params[:id])
	    @comment = current_user.hobby_comments.new(hobby_id: @hobby.id)
	    @comments = @hobby.hobby_comments.all.page(params[:page])
	  end

**Comment by jun0033** [comment]
とても参考になります。
使っていないインスタンス変数を定義したままでした。
ありがとうございます
