### ISSUE TITLE
コードレビュー：show.html.erb

### ISSUE THREAD

**Issue by yuki-nishimoto1109** [jun0033/osituke_app#59]
# show.html.erb
主な変更点
 1. テンプレート化

## 1. テンプレート化
趣味を表示する部分をテンプレート化
一覧表示の際のものとは表示が異なるため、別テンプレートで用意
*注意：テンプレート化した際に、user/tagsなどのインスタンス変数はuserからのアソシエーションで参照できるように変更

---
[元コード省略]

---
    [最終コード]
	<div class="container text-center wrap">
	  <%= render "public/hobbies/hobby_display_one", hobby: @hobby %>

	  <%= @hobby.hobby_comments.count %> コメント
	  <%= render "public/hobby_comments/comments_index", comments: @comments %>
	  <%= paginate @comments, theme: 'twitter-bootstrap-4' %>
	</div>
	
	<%= render "public/hobby_comments/comment_form" %>
	<% unless @hobby.done_by?(current_user) %>
	  <%= render "public/hobby_comments/done_form" %>
	<% end %>
---

    [_hobby_display_one.html.erb]
    <div class="row my-3 mx-5 p-1" style="background-color: #d4ecea;">
      <div class="col-2 text-right mt-1">
        <%= image_tag hobby.user.get_profile_image(80,80) %>
      </div>
      <div class="col-2 col-sm-2 text-left">
       <h5><%= link_to hobby.user.name, user_path(hobby.user.id) %></h5>
      </div>
      <div class="col-8 col-sm-8 text-left p-2">
        <div class="row">
          <h4 class="col-5"><%= hobby.title %></h4>
          <div class="col-4 d-flex">
            <%= render "stars/star_average", hobby: hobby %>
          </div>
          <div class="col-3 text-center">
            <%= link_to genre_path(hobby.genre.id), class: "btn btn-outline-info rounded-pill" do %>
            <i class="fas fa-tag"></i>
            <%= hobby.genre.genre_name %>
            <% end %>
          </div>
        </div>
        <div class="row" style="width: 100%;">
          
          <%= safe_join(hobby.body.split("\n"),tag(:br)) %>
        </div>
        <div class="row">
          <% hobby.hobby_images.each do |hobby_image| %>
          <%= image_tag(hobby_image, width:100, height:100 )%>
          <% end %>
        </div>
        <div class="row mt-1">
          <% hobby.tags.each do |tag| %>
            #<%= link_to tag.tag_name, tag_path(tag) %>
          <% end %>
        </div>
        <div class="row mt-1">
          <div class="col-4" id="favorite_buttons_<%= hobby.id %>">
            <%= render "public/favorites/favorite", hobby: hobby %>
          </div>
          <div class="col-4" id="todo_buttons_<%= hobby.id %>">
            <%= render "public/to_does/to_do", hobby: hobby %>
          </div>
          <div class= "col-2 text-right" style="opacity: 0.5;">
            <%= hobby.how_long_ago %>
          </div>
          <% if hobby.user.id == current_user.id %>
            <div class="col-1">
              <%= link_to edit_hobby_path(hobby.id), style: "right: 5px;" do %>
                <i class="fas fa-cogs"></i>
              <% end %>
            </div>
            <div class="col-1">
              <%= link_to hobby_path(hobby.id), method: :delete, style: "right: 5px;", data: { confirm: "【確認】趣味を削除してもよろしいですか？" } do %>
                <i class="fas fa-trash fa-lg"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

**Comment by jun0033** [comment]
[_hobby_display.html.erb]
```
<div class="row my-3 mx-5 p-1 border-color wrap">
  <div class="col-2 text-right mt-1">
    <%= image_tag hobby.user.get_profile_image(80,80), class: "rounded-circle border border-dark" %>
  </div>
  <div class="col-2 col-sm-2 text-left">
    <h5><%= link_to hobby.user.name, user_path(hobby.user.id) %></h5>
  </div>
  <div class="col-8 col-sm-8 text-left p-2">
    <div class="row">
      <h4  class="col-5"><%= link_to "#{hobby.title}", hobby_path(hobby) %></h4>
      <div class="col-4 d-flex"><%= render "stars/star_average", hobby: hobby %></div>
      <div class="col-3 text-center">
        <%= link_to genre_path(hobby.genre.id), class: "btn btn-outline-info rounded-pill" do %>
          <i class="fas fa-tag"></i><%= hobby.genre.genre_name %>
        <% end %>
      </div>
    </div>
    <div class="row" style="width: 100%;">
      <%= safe_join(hobby.body.split("\n"),tag(:br)) %> <!--ユーザーのつけた段落を反映-->
    </div>
    <div class="row">
      <% hobby.hobby_images.each do |hobby_image| %>
        <%= image_tag(hobby_image, width:100, height:100 )%>
      <% end %>
    </div>
    <div class="row mt-1">
      <div class="col-3" id="favorite_buttons_<%= hobby.id %>">
        <%= render "public/favorites/favorite", hobby: hobby %>
      </div>
      <div class="col-2">
        <%= link_to hobby_path(hobby) do %>
        <%= hobby.hobby_comments.count %> コメント
        <% end %>
      </div>
      <div class="col-3" id="todo_buttons_<%= hobby.id %>">
        <%= render "public/to_does/to_do", hobby: hobby %>
      </div>
      <div class= "col-2 text-right" style="opacity: 0.5;">
        <%= hobby.how_long_ago %>
      </div>
      <% if hobby.user.id == current_user.id %>
        <div class="col-1">
          <%= link_to edit_hobby_path(hobby), style: "right: 5px;" do %>
            <i class="fas fa-cogs"></i>
          <% end %>
        </div>
        <div class="col-1">
          <%= link_to hobby_path(hobby), method: :delete, style: "right: 5px;", data: { confirm: "【確認】趣味を削除してもよろしいですか？" } do %>
            <i class="fas fa-trash fa-lg"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
```
この記述を共通の部分テンプレートに採用し、showだけ記述が違う問題を

[show.html.erb]
```
<div class="container text-center wrap">
  <%= render "public/hobbies/hobby_display", hobby: @hobby %>
  <h5 class="alert alert-info border border-dark text-center">コメント一覧</h5>
  <%= render "public/hobby_comments/comments_index", comments: @comments %>
  <%= paginate @comments, theme: 'twitter-bootstrap-4' %>
</div>
```
とすることで共通部分テンプレートを使いまわすことにしました！

全体で投稿を表示していた箇所全てにこの部分テンプレートを使うことにより、大分コードが見やすくなり記述も減らすことができました！
ご意見ありがとうございます！
